### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by amroto** [ignaciouy/GCILeaderboard#22]
number of closed tasks in FOSS ASIA should be 517 not 500

**Comment by SAMdroid-apps** [comment]
Hi @amroto, I just triggered a cache update.

Just wondering, where did you get this 517 number from?

**Comment by amroto** [comment]
Open fossasia from home page and see the number of closed tasks

**Comment by SAMdroid-apps** [comment]
Hum, I see.

I checked a bunch of other things by going to the GCI home page and looking about.  It appears to be specific to the FOSS Asia org.

Does FOSS Asia do anything weird?  Are they reusing tasks for multiple contributes?  Do you know @ty221?

**Comment by amroto** [comment]
Some tasks are re-posted spexially those where you can learn something like pharo tasks and yes I know @ty221

**Comment by amroto** [comment]
specially*

**Comment by ty221** [comment]
Hi,

there is mistake in update.py script. It seeks only maximum 500 tasks:

BASEURL = "http://www.google-melange.com/gci/org/google/gci2014/" \
    "{orgname}?fmt=json&limit=500&idx=1"

I have changed that, should work now

**Comment by amroto** [comment]
nope still bugged

**Comment by ty221** [comment]
Because we need to wait for restart

Fri Jan 16 2015 at 15:56:49 użytkownik amroto <notifications@github.com>
napisał:

**Comment by SAMdroid-apps** [comment]
I think I just restarted it :smile:
